### ISSUE TITLE
error

### ISSUE THREAD

**Issue by bouhlal** [cytech/scheduler-InvoiceNinja#3]
Hello
i tried to install it but i got this error :
test]$ php artisan module:install cytech/scheduler --type=github
PHP Parse error:  syntax error, unexpected ')' in /home/test/public_html/test/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php on line 233

**Comment by cytech** [comment]
This project is over 2 years old and has not been updated with InvoiceNinja.
It was never popular enough to upkeep and i use a different solution now.
I will be deleting the repository or abandoning it.

**Comment by cytech** [comment]
archived
